title: >
  Concepts of Programming Languages (CS421/521, Fall 2020)

description: >
  Material for UWL CS421/521 (Concepts of Programming Languages), Fall 2020

license: Creative Commons Attribution 4.0 International License
license-file: https://creativecommons.org/licenses/by/4.0/

repository: jphmrst/plfa.github.io
branch: dev

baseurl: ""
url: "https://plfa.github.io"
markdown: kramdown
theme: minima
exclude:
  - "hs/"
  - "extra/"
  - "depr/"
  - "papers/"
  - "slides/"
  - "vendor/"
  - "*.agdai"
  - "*.agda-lib"
  - "*.lagda.md"
  - "Guardfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "highlight.sh"
  - "out/epub/acknowledgements.md"
